### ISSUE TITLE
feedback: built-in pretty-printer

### ISSUE THREAD

**Issue by rprimet** [Deducteam/Logipedia#15]
Hi all,

Even though I see the case for pluggable pretty-printers, the current ones required dependencies that were not packaged in stable debian and the pretty-printers themselves were not packaged (a straightforward install seems really important to help simplify the CI pipeline).

So I made a quick port of the LogiPPedia pretty-printer and added it to the static generator.

I think it makes sense to provide a default implementation and we'll be able to make a pluggable, command-line pretty-printer later if/when the need arises.

Thoughts?

**Comment by gabrielhdt** [comment]
I can ease the install of the pretty printer in the Makefile as well.  The scheme pretty printer I have is already a bit sophisticated.  It is a good idea to provide a built-in default, but I think we already need more

**Comment by rprimet** [comment]
OK ; do you think you could backport the improvements you made to the scheme pp into the python one or do you prefer streamlining the install and removing the python code? (if possible, something we could install on a regular debian?)

**Comment by gabrielhdt** [comment]
IMO, the python code can remain even though the makefile contains a target to install the scheme pp

**Comment by rprimet** [comment]
Makes sense, but then I'd like to have the built-in code at least marginally useful and tested... I'll see if we can keep somewhat up-to-date with the scheme one, otherwise it's probably better to just delete it or replace it by a no-op pretty printer?
