### ISSUE TITLE
Are the mongo / bson packages outdated?

### ISSUE THREAD

**Issue by rprimet** [Deducteam/Logipedia#2]
Hi,

I am trying to build logipedia as per the README instructions. 

My attempt to install the ocaml `mongo` driver with `opam install mongo` fails with the error:

```
romain@plume:~$ opam install mongo
The following dependencies couldn't be met:
  - mongo → bson >= 0.89.3 → ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)

No solution found, exiting
```

```
romain@plume:~$ opam list
# Packages matching: installed
# Name              # Installed # Synopsis
base-bigarray       base
base-threads        base
base-unix           base
conf-m4             1           Virtual package relying on m4
dedukti             2.6.0       The Dedukti logical framework
menhir              20181113    An LR(1) parser generator
ocaml               4.07.1      The OCaml compiler (virtual package)
ocaml-base-compiler 4.07.1      Official release 4.07.1
ocaml-config        1           OCaml Switch Configuration
ocamlbuild          0.14.0      OCamlbuild is a build system with builtin rules 
ocamlfind           1.8.0       A library manager for OCaml
```

According to the opam website, `mongo` and its dependency `bson` were last released in 2014.

Is there any workaround for that?

Does that mean that we are locked to ocaml < 4.06 going forward?

Apologies for any misunderstandings / basic mistakes, I am a complete ocaml novice.

**Comment by francoisthire** [comment]
Currently, yes. However, on the long run, probably it is a good idea to drop MongoDB and hence the OCaml dependency too.

**Comment by francoisthire** [comment]
A workaround would be to maintain a fork of `mongo` and changing the version constraint I guess. In the meantime, you can also have your own fork.
