### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Logipedia#31]
The files HACKING.md and README.md are outdated. Probably HACKING.md should be removed and README.md should reference the `doc` sooner.

**Comment by gabrielhdt** [comment]
Readme.md is not that outdated, is it?

**Comment by francoisthire** [comment]
Indeed, but I think it should be rewritten. Probably because there is now a `doc` folder, the top-level README should contain only (are almost) a link to that folder instead.

**Comment by gabrielhdt** [comment]
90365ee3e8d401adeea8b53134bd7c4d432733f9
