### ISSUE TITLE
provide a flag to choose output system(s)

### ISSUE THREAD

**Issue by rprimet** [Deducteam/Logipedia#5]
In the export code, it may be useful to be able to configure / choose output systems at run time. This may help provide quicker checks especially as most time seems to be spent in the exporter for a single system (opentheory).

**Comment by gabrielhdt** [comment]
Currently, there is one `make` target per system.  Assuming `make coq` has been run, coq files are lying in `export/coq`.  Generating json only using coq files is simply a matter of `logipedia json --coq export/coq -o export/json -f path/to/file.dk`.

Do you need more?

**Comment by rprimet** [comment]
LGTM, I don't think we need more!
